module.exports = {
  heading: 'Privacy Policy',
  subheading: '1. Data protection overview',
  smalheading: 'General information',
  text1:
    'The following information provides a simple overview of what happens to your personal data when you visit our website. Personal data are all data with which you can be personally identified. You can find detailed information on the subject of data protection in our data protection declaration below this text. Data collection on our website Who is responsible for data collection on this website? The data processing on this website is carried out by the website operator. You can find their contact details in the imprint of this website. How do we collect your data? On the one hand, your data is collected by you communicating it to us. This can e.g. are data that you enter in a contact form. Our IT systems automatically collect other data when you visit the website. This is primarily technical data (e.g. internet browser, operating system or time of page access). This data is recorded automatically as soon as you enter our website. What do we use your data for? Part of the data is collected to ensure that the website is provided correctly. Other data can be used to analyze your user behavior. What rights do you have regarding your data? You have the right to receive information about the origin, recipient and purpose of your stored personal data at any time free of charge. You also have the right to request that this data be corrected, blocked or deleted. You can contact us at any time at the address given in the imprint if you have any further questions about data protection. You also have the right to lodge a complaint with the responsible supervisory authority. You also have the right to request that the processing of your personal data be restricted in certain circumstances. You can find details on this in the data protection declaration under "Right to restriction of processing". Analysis tools and tools from third-party providers When you visit our website, your surfing behavior can be statistically evaluated. This is done primarily with cookies and with so-called analysis programs. Your surfing behavior is usually analyzed anonymously; the surfing behavior cannot be traced back to you. You can object to this analysis or prevent it by not using certain tools. You can find detailed information on this in the following data protection declaration. You can object to this analysis. We will inform you about the possibilities of objection in this data protection declaration.',
  subheading2: '2. General information and mandatory information',
  smalheading2: 'Privacy Policy',
  text2:
    'The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this data protection declaration. When you use this website, various personal data are collected. Personal data is data with which you can be personally identified. This data protection declaration explains what data we collect and what we use it for. It also explains how and for what purpose this is done. We would like to point out that data transmission over the Internet (e.g. when communicating by email) can have security gaps. It is not possible to completely protect data from third-party access. Information about the responsible body',
  text3: 'The responsible body for data processing on this website is:',
  text4:
    'The responsible body is the natural or legal person who, alone or together with others, decides on the purposes and means of processing personal data (e.g. names, email addresses, etc.).',
  smalheading3: 'Revocation of your consent to data processing',
  text5:
    'Many data processing operations are only possible with your express consent. You can withdraw your consent at any time. An informal notification by email to us is sufficient. The legality of the data processing carried out before the revocation remains unaffected by the revocation. Right to object to data collection in special cases and direct advertising (Art. 21 GDPR) if data processing is based on Art. 6 Para. 1 lit. e or f GDPR, you have the right to object to the processing of your personal data at any time for reasons that arise from your particular situation; this also applies to profiling based on these provisions. The respective legal basis on which processing is based can be found in this data protection declaration. If you file an objection, we will no longer process your personal data concerned, unless we can demonstrate compelling legitimate grounds for the processing that outweigh your interests, rights and freedoms or the processing serves to assert, exercise or defend legal claims ( Objection according to Art. 21 Para. 1 GDPR). If your personal data are processed for direct marketing purposes, you have the right to object at any time to the processing of your personal data for the purpose of such advertising; this also applies to profiling insofar as it is connected to such direct advertising. If you object, your personal data will then no longer be used for direct marketing purposes (objection under Art. 21 Para. 2 GDPR). Right to lodge a complaint with the competent supervisory authority In the event of violations of the GDPR, the data subject has the right to lodge a complaint with a supervisory authority, in particular in the member state of their habitual residence, their place of work or the place of the alleged violation. The right to lodge a complaint is without prejudice to other administrative or judicial remedies. Right to data portability You have the right to have data that we process automatically based on your consent or in fulfillment of a contract handed over to you or to a third party in a common, machine-readable format. If you request the direct transfer of the data to another person responsible, this will only take place if it is technically feasible.',
  smalheading4: 'SSL or TLS encryption',
  text6:
    'For security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as the site operator, this site uses an SSL or. TLS encryption. You can recognize an encrypted connection by the fact that the address line of the browser changes from “http: //” to “https: //” and by the lock symbol in your browser line. If SSL or TLS encryption is activated, the data that you transmit to us cannot be read by third parties.'
}
